# Generated by Django 3.1.7 on 2021-03-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
