# Generated by Django 3.1.7 on 2021-03-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VBlog', '0005_auto_20210327_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Categories',
            field=models.CharField(default='uncategorised', max_length=255),
        ),
    ]
