# Generated by Django 3.1.7 on 2021-03-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VBlog', '0009_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='Posters/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(max_length=255),
        ),
    ]
