# Generated by Django 3.1.7 on 2021-03-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VBlog', '0010_auto_20210330_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default='/media/Posters/intro-1.jpeg', upload_to='Posters/'),
        ),
    ]
