# Generated by Django 3.1.7 on 2021-03-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VBlog', '0011_auto_20210330_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='Poster',
        ),
    ]
