# Generated by Django 3.1.7 on 2021-03-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VBlog', '0014_auto_20210330_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Poster',
            field=models.ImageField(default='/Poster/intro-1.jpeg', upload_to='Posters/'),
        ),
    ]
