# Generated by Django 3.1.7 on 2021-03-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VBlog', '0018_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Profile_pic',
            field=models.ImageField(default='/Posters/intro-1.jpeg', upload_to='Profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_website_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
