# Generated by Django 3.1.7 on 2021-04-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VBlog', '0021_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
