# Generated by Django 3.1.7 on 2021-04-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VBlog', '0022_remove_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='VBlog.IpModel'),
        ),
    ]
