# Generated by Django 3.1.7 on 2021-04-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VBlog', '0023_auto_20210402_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
