# Generated by Django 3.1.7 on 2021-04-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VBlog', '0024_remove_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='Meta_Titles',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
