# Generated by Django 3.1.7 on 2021-04-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VBlog', '0032_categories_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thoughts',
        ),
    ]
